apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-deployment
  namespace: argo-app
  labels:
    app: basic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: basic-app
  template:
    metadata:
      labels:
        app: basic-app
    spec:
      containers:
      - name: basic-container
        image: nginx:1.21.6 # Specific version for easier updates
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: basic-service
  namespace: argo-app
spec:
  selector:
    app: basic-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP